### ISSUE TITLE
User Administration app: DOWNLOAD TO CSV is not working

### ISSUE THREAD

**Issue by Nazdar10** [pepfar-datim/datim-user-management-ng#194] opened 2019-06-26 20:20 UTC
@jakub-bao 
ENV: ng.testing.datim.
Nothing is downloaded when clicking on the download to csv button in the user admin app. In order to duplicate this issue: Click on DOWNLOAD TO CSV BUTTON on the top right corner of the user admin.  "downloading" is displayed for a few seconds but then it stops and nothing is downloaded. I cleared cache and tried again with no success

![image](https://user-images.githubusercontent.com/50021119/60211693-9d35a680-982d-11e9-9130-cbf897d2aa29.png)

@hkim224

**Comment by jakub-bao** [comment] 2019-06-27 15:14
nice. good catch. thanx!

cc: @benguaraldi

**Comment by jakub-bao** [comment] 2019-06-27 15:22
actually.. it is working.. it just takes forever.. :/ 

Because in the example above it's generating a report about 20k users...

this is mostly because you're accessing it as a super user.
no-one else should have access to 20k users...

**Comment by jakub-bao** [comment] 2019-06-27 17:08
let me see what i can do to maybe give a little bit more feedback to user that the process is in progress...

**Comment by jakub-bao** [comment] 2019-06-27 17:11
so it's an issue only for Global users... but it is an issue in fact. will do something about it.

**Comment by jakub-bao** [comment] 2019-06-27 17:30
@hkim224 @Nazdar10 @benguaraldi 

Just to re-iterate:
 
- The export of 22k users does take 1-2 minutes :(
+ It only affects Global users. 

Is this a good solution?

![image](https://user-images.githubusercontent.com/47790868/60287371-b1d27700-98df-11e9-9f8c-cb5630f3589e.png)

**Comment by benguaraldi** [comment] 2019-06-27 17:42
Does it take this long in the angular app?

**Comment by Nazdar10** [comment] 2019-06-27 17:50
@jakub-bao The issue in ng-test Env is not that it takes 2-3 minutes, it times out after about 60 seconds. Is this a fix you are recommending? to allow it take up to 2-3 minutes to download the list? 
@benguaraldi Which one is the angular app?

**Comment by jakub-bao** [comment] 2019-06-27 20:34
@Nazdar10 oh got you!! i just tried... oh, not good :(

@benguaraldi yes, i think it's actually even slower.. https://dev-jakub.datim.org/api/apps/User-Administration/index.html?v=1.2.1#/list

@benguaraldi FYI, there are three steps involved

- step #1 processing query on server-side. this takes about 30% of the time. 
- step #2 data transfer between server and client. another 30%.
- step #3 processing JSON data into CSV on front-end: 40% here.

note: as Naz says, it times out on step #1 for ng.testing.

Solutions:
1. talk to Chuq and find out why it times out on step #1 on ng.testing. probably nginx / tomcat settings.
2. check if we can shrink the query to put less load on server during step #1 and also reduce amount of data to be transferred in step #3
3. it will be probably possible to try to optimize step #3 
4. another reasonable solution would be to have two exports. quick export and full export. full export is the current one (it exports all fields including, groups, roles, etc.). we can do a quick export which would aim for username, email, usertype, etc. that would be fast.

**Comment by benguaraldi** [comment] 2019-06-28 04:30
@jakub-bao Got it.  Then I don't think this is MVP if it's even slower in the angular version.  Probably something that works on production but not ng.testing.

Let's talk to @chuqyang and @Lownin about the timeout and see if the settings are different in ng.testing than production.  If it runs at all on production, then I think optimizing the query or adding a quick export is lower priority.

Thanks!

**Comment by jakub-bao** [comment] 2019-06-28 14:23
@benguaraldi It's now working on `ng.testing` with the new timeout.

However, I agree this shouldn't be our final solution.
I'd like to take a look on this issue closely sometime and see if we can optimize (shrink) the API call.

![image](https://user-images.githubusercontent.com/47790868/60349037-cd488b00-998e-11e9-8c21-5347513113ad.png)

**Comment by benguaraldi** [comment] 2019-06-28 14:26
@jakub-bao I'm a little unclear why it needs a longer timeout for the react app than the angular app. Maybe ng.testing is simply slower than production so on production it wouldn't need the longer timeout?  If that's the case, we could still optimize the query, but it might not be necessary for MVP.

**Comment by jakub-bao** [comment] 2019-06-28 14:36
@benguaraldi 
> @jakub-bao I'm a little unclear why it needs a longer timeout for the react app than the angular app. 

I don't think that's the case. It needs 2-3 minute timeout for both versions.

I think the issue is with our 2.29 vs 2.30 deployment. 2.29 servers seem to have ~5min timeout by default, while 2.30 had 60second timeout.

It makes sense because they run on different webservers.

cc: @chuqyang

**Comment by benguaraldi** [comment] 2019-06-28 14:37
@chuqyang Can you confirm the timeout differences?

**Comment by jakub-bao** [comment] 2019-06-28 14:37
@benguaraldi FYI, here you can see CPU profile from Chrome Devtools.
CPU processing of the data (the thing re-written in REACT) seems to take only 15s.
Majority of the time is idle => waiting for network.

![image](https://user-images.githubusercontent.com/47790868/60350064-c9b60380-9990-11e9-9881-2384eb11d268.png)

**Comment by benguaraldi** [comment] 2019-06-28 14:47
Thanks, @jakub-bao.

@chuqyang, can you confirm that the timeout for production and some dev/testing servers is set to 5 minutes?  If that's true, can we assume that that's going to remain the same when we deploy 2.30?

If not, I imagine a whole bunch of things are going to break in addition to this.

**Comment by chuqyang** [comment] 2019-06-28 15:34
on www.datim.org, the nginx timeouts are:

```
      proxy_connect_timeout  300s;
      proxy_read_timeout     300s;
      proxy_send_timeout     300s;
```

Same on test.datim.org.

On dev.datim.org, it is a whopping 20 minutes: 

```
      proxy_connect_timeout  1200s;
      proxy_read_timeout     1200s;
      proxy_send_timeout     1200s;
```

We can keep the 300s timeout on production with 2.30.

**Comment by benguaraldi** [comment] 2019-06-28 16:17
20 minutes?!?  That's awesome.  Thanks, @chuqyang.

@Nazdar10, please confirm this is fixed on ng.testing and then close this ticket.

@jakub-bao, please make a separate ticket for any optimization that you want to do to this function.

Thanks!

**Comment by Nazdar10** [comment] 2019-06-28 16:28
@benguaraldi @jakub-bao 
I was able to download the csv but the message "Exporting list of 30387 users. This will take about 2-3 minutes." did not go away and is still displayed after the export was complete. 

![image](https://user-images.githubusercontent.com/50021119/60356434-f83adb00-999e-11e9-8ee0-9d8eb18d393a.png)


![image](https://user-images.githubusercontent.com/50021119/60356758-d2620600-999f-11e9-8b9f-9ec0970bf4c7.png)

**Comment by chuqyang** [comment] 2019-06-28 16:28
> 20 minutes?!? That's awesome. 

I'm guessing one of the devs did this...

**Comment by benguaraldi** [comment] 2019-06-28 18:02
Thanks, @Nazdar10!  @jakub-bao, let us know if you'd prefer a different ticket for the message not going away.

**Closed** 2020-05-11 19:17 UTC
